name: Build Census App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # استخدام حاوية جاهزة تتجنب خطأ 100 وتدعم Node 24
    container:
      image: ghcr.io/kivy/buildozer:master

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          # نحن الآن داخل بيئة Kivy الرسمية، لا داعي لتثبيت أي شيء
          # فقط نقوم بالبناء مباشرة
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Census-Final-APK
          path: bin/*.apk
          
