name: Build Kivy App (Census 2026)
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # حل تنبيه Node.js وتوجيه السيرفر لاستخدام النسخة الأحدث
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          # حل خطأ 100 عن طريق تحديث المستودعات وإصلاح الحزم المعطلة
          sudo apt-get update --fix-missing
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev python3-dev \
            libncurses5 libncursesw5-dev zlib1g-dev zip unzip autoconf automake libtool \
            pkg-config python3-pip
          
          # تثبيت أدوات البناء الأساسية
          python -m pip install --upgrade pip
          pip install buildozer kivy

      - name: Build with Buildozer
        run: |
          # أمر واحد يقوم بكل شيء: قبول التراخيص وبناء التطبيق
          yes | buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Census-2026-App
          path: bin/*.apk
